import "./globals.css";
// import { ThemeProvider } from "next-themes";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={"dark"}>
      <body>
        {" "}
        <div className=" dark:bg-slate-900  dark:text-white bg-gray-400 ">
          {children}
        </div>
      </body>
    </html>
  );
}
