import Header from "./components/header";
import AuthProvider from "./context/authProvider";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <Header />
        <body>{children}</body>
      </AuthProvider>
    </html>
  );
}
