import AuthProvider from "@/context/authProvider";
import Header from "./components/header";

// import AuthProvider from "./context/authProvider";
import "./globals.css";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
<<<<<<< HEAD
        <AuthProvider>{children}</AuthProvider>
=======
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
>>>>>>> a2f0a1b ("more new features added in authentication next js")
      </body>
    </html>
  );
}
