import AuthProvider from "@/context/authProvider";
import Header from "./components/header";
import { cookies } from "next/headers";
// import AuthProvider from "./context/authProvider";
import "./globals.css";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const nextToken = cookieStore.get("next-auth.session-token");
  console.log(nextToken);
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {nextToken?.value ? <Header /> : null}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
